apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-nudj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-nudj
    app.kubernetes.io/part-of: test-app-iuea
  name: test-component-nudj
  namespace: build-e2e-boxn-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-nudj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-nudj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:b3215b1bfffe05926215c53e51454525656b9262670d7e9fd60370eab8a557d1
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
